### PR TITLE
Implement feature 6

### PR DESCRIPTION
**Pull request by lattilaCosylab**

### CODE REVIEW

**Review by ryanfordSLAC — COMMENTED** [review]
Is the new logic for this feature implemented in alert1()?  See line 662 of ScannerViewController.

**Review by ryanfordSLAC — COMMENTED** [review]
Alert12:  please change message slightly

let message = "Invalid barcode, please rescan!"

**Comment by lattilaCosylab** [comment]
Yes, the main problem is in line 945 and 949... If here the dosiNumber or the QRCode is nil, then it will save the "Nil Dosi" or "Nil QRCode" value. With the current fix, it cannot be nil here.
________________________________
Feladó: Ryan Ford ***@***.***>
Elküldve: 2023. május 15., hétfő 17:39
Címzett: ryanfordSLAC/DosiXchange2 ***@***.***>
Másolatot kap: Attila Lakatos ***@***.***>; Author ***@***.***>
Tárgy: Re: [ryanfordSLAC/DosiXchange2] Implement feature 6 (PR #18)

Ritkán kap e-mailt a(z) ***@***.*** e-mail-címről. Miért fontos ez?<https://aka.ms/LearnAboutSenderIdentification>
Caution: This email originated from outside of Cosylab.


@ryanfordSLAC commented on this pull request.

Is the new logic for this feature implemented in alert1()? See line 662 of ScannerViewController.

**Review by ryanfordSLAC — COMMENTED** [review]
Alert12: please change message slightly

let message = "Invalid barcode, please rescan!"

(same comment as yesterday

**Comment by lattilaCosylab** [comment]
I replaced the text of the message!

**Review by ryanfordSLAC — APPROVED** [review]
Looks good.

**Pull request merged**
