### PR TITLE
locations dispatchgroup changed to semaphore

### PR DESCRIPTION
**Pull request by laszollosi**
The dispatchgroup thread safety wasn't a good solution, so I rewrite to the good old semaphore way.

### CODE REVIEW

**Review by ryanfordSLAC — APPROVED** [review]
Thanks, I learned something today.

**Comment by ryanfordSLAC** [comment]
This works in the simulator but won't install to my phone.

image

**Comment by ryanfordSLAC** [comment]
This is the output I get when I build to the simulator:

Reachable via WiFi
Location query started
This request requires an authenticated account
Cloudkit user: 
Location query completed.
Location query started
Location query completed.
Synchronization from reachability
Completed: 534.0
Deployed: 541.0
Progress: 0.987061
Your request contains 3989 items which is more than the maximum number of items in a single request (400)

**Comment by laszollosi** [comment]
Hmm, have you tried to run the report group update at tools?

**Comment by ryanfordSLAC** [comment]
I ran it yesterday in Development, but I think you had already run it there.  I couldn't run it from my iPhone this morning because the app wouldn't load.  When I ran on the simulator I clicked the Tools 5 times but nothing in CloudKit changed.

**Comment by ryanfordSLAC** [comment]
Yes, the clean build worked thank you.

**Pull request merged**
