### PR TITLE
Bugfix batch save

### PR DESCRIPTION
**Pull request by laszollosi**
I've successfully tested on development environment. It should be good on prod, please test.

### CODE REVIEW

**Comment by laszollosi** [comment]
Making a backup from production would be advisable. Please delete your application before updating report groups.

**Comment by ryanfordSLAC** [comment]
> Making a backup from production would be advisable. Please delete your application before updating report groups.

The only way I know how to make a backup of production is to export the data as CSV.

**Review by ryanfordSLAC — APPROVED** [review]
Looks good.

**Comment by ryanfordSLAC** [comment]
[Dosi_Data10.csv](https://github.com/ryanfordSLAC/DosiXchange2/files/11576925/Dosi_Data10.csv)

Most recent export

**Comment by ryanfordSLAC** [comment]
If you look at what the raw CSV looks like in TextEdit, you can see the spaces.  The remainder of the string is built without the leading space.


BLG 006-008,37.41744,-122.20252,RGD#56: Titan Krios #1: Room 110,0,1,BA00047597T,1,7-1-2019,08/12/2019,05/26/2023,0,08/12/2019,05/26/2023, 8C4D44C7-48F0-4DEB-B275-577527C8D7CB, Ryan Ford, GEN

**Comment by ryanfordSLAC** [comment]
Also, you can disable the 5-tap dev function.  It has been run and is not needed anymore.  You can leave the code just disable the trigger.

**Pull request merged**
