### PR TITLE
Feature cache

### PR DESCRIPTION
**Pull request by laszollosi**
Hi,
The new cache is fully implemented. It completes the following work items: 2, 5, 11, 12, 13, 14, 16.
Before testing, please delete the previous build from your device.

### CODE REVIEW

**Comment by ryanfordSLAC** [comment]
IMG-3748
IMG-3747
Hi Laszio, I tested my first dosimeter in Development and it shows correctly in "All Locations", however, the search bar isn't working.  The new dosimeter is SSRL-81, but when I type SSRL or 81 it doesn't produce any results.  (It did before).

**Comment by ryanfordSLAC** [comment]
I tested Mismatch toggle and it's leaving the field in Cloudkit as Nil.  This is fine, we don't need the field, but if this was intended please remove the toggle from the Edit Record view.  Otherwise the mismatch toggle should create and save a 1 or 0 to the field in CloudKit like the other fields.

**Comment by ryanfordSLAC** [comment]
I'm assuming you created the record "ALPINE-4" in Dev. Just a note you can only have one dosimeter per cycle per location.  In this case you have 4 dosimeters same cycle same location.  You can edit in cloudkit (and the app now!) to change the cycles progressively backward so 1 dosimeter per cycle per location.

**Comment by ryanfordSLAC** [comment]
The "Back" button from All Locations behaved strangely although I'm having difficulty reproducing it.  The back button took about 10 clicks to get back to the Tools VC.  Seems it captured an instance of the whole trail through multiple dosimeters and forced me to backtrack through them sequentially to return to Tools VC.  Should be only one click of 'back' to return to Tools VC from All Locations.

**Comment by ryanfordSLAC** [comment]
App crashed twice upon scan of SSRL-81 (for collection).  Crashed twice on Code128 barcode.  Relaunched and worked with QR Code and Code128 barcodes.  

Then I switched the Active Toggle to Inactive, and attempted to collect only (Alert 3i), and on the Code 128 it crashes continuously (can't complete any action).

**Comment by ryanfordSLAC** [comment]
Beautiful job on the offline mode.  I deployed a dosimeter while offline and checked the cloudkit (it wasn't there).  Then I turned on Wifi and refreshed the cloud and the record was there.  Great!  Might I ask if the scanner view is also grey while offline?

**Comment by laszollosi** [comment]
> IMG-3748 IMG-3747 Hi Laszio, I tested my first dosimeter in Development and it shows correctly in "All Locations", however, the search bar isn't working. The new dosimeter is SSRL-81, but when I type SSRL or 81 it doesn't produce any results. (It did before).

All the queries in the VCs are working from in memory "database", and the search based on the search field was case sensitive, I've fixed it.

**Comment by laszollosi** [comment]
> I tested Mismatch toggle and it's leaving the field in Cloudkit as Nil. This is fine, we don't need the field, but if this was intended please remove the toggle from the Edit Record view. Otherwise the mismatch toggle should create and save a 1 or 0 to the field in CloudKit like the other fields.

Yes, it wasn't saved before. It's saved  now with the rest of the fields.

**Comment by laszollosi** [comment]
> The "Back" button from All Locations behaved strangely although I'm having difficulty reproducing it. The back button took about 10 clicks to get back to the Tools VC. Seems it captured an instance of the whole trail through multiple dosimeters and forced me to backtrack through them sequentially to return to Tools VC. Should be only one click of 'back' to return to Tools VC from All Locations.

The navigation was messed up when status changed in location details, fixed it.

**Comment by laszollosi** [comment]
> App crashed twice upon scan of SSRL-81 (for exchange). Crashed twice on Code128 barcode. Relaunched and worked with QR Code and Code128 barcodes.
> 
> Then I switched the Active Toggle to Inactive, and attempted to collect only (Alert 3i), and on the Code 128 it crashes continuously (can't complete any action).

A self nil reference caused the crash when we're querying for the dosimeters, fixed it.

**Comment by laszollosi** [comment]
> Beautiful job on the offline mode. I deployed a dosimeter while offline and checked the cloudkit (it wasn't there). Then I turned on Wifi and refreshed the cloud and the record was there. Great! Might I ask to change the scanner view to grey while offline?

Thanks. :) It's grey now.

**Review by ryanfordSLAC — APPROVED** [review]
No comments.

**Pull request merged**
